<?xml version="1.0" encoding="utf-8"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\boyerp\Dropbox\Github\Autodesk\DynamoNew\Dynamo\bin\AnyCPU\Debug\DynamoTestFramework.dll" total="2" failures="1" not-run="0" date="2013-12-11" time="19:32:56" errors="0" inconclusive="0" ignored="0" skipped="0" invalid="0">
  <test-suite name="DynamoTestFrameworkTests" description="Unit tests in Revit." time="2.080208" asserts="7" type="TestFixture" result="Failure" executed="True">
    <results>
      <test-suite name="ModelTextTests" description="Unit tests in Revit." time="2.080208" asserts="7" type="TestFixture" result="Failure" executed="True">
        <results>
          <test-case name="ByTextSketchPlaneAndPosition_ValidArgs" success="True" time="1.0461046" executed="True" asserts="3" result="Success" />
          <test-case name="ByTextSketchPlaneAndPosition_BadArgs" success="False" time="1.0341034" executed="True" asserts="4" result="Failure">
            <failure>
              <message>  Expected: &lt;System.ArgumentNullException&gt;
  But was:  &lt;Autodesk.Revit.Exceptions.ArgumentNullException&gt; (Value cannot be null.
Parameter name: text)
   at Autodesk.Revit.Creation.FamilyItemFactory.NewModelText(String text, ModelTextType modelTextType, SketchPlane sketchPlane, XYZ position, HorizontalAlign horizontalAlign, Double depth)
   at DSRevitNodes.Elements.DSModelText.CreateModelText(String text, SketchPlane sketchPlane, Double xCoordinateInPlane, Double yCoordinateInPlane, Double textDepth, ModelTextType modelTextType) in c:\Users\boyerp\Dropbox\Github\Autodesk\DynamoNew\Dynamo\src\DSRevitNodes\Elements\DSModelText.cs:line 201
   at DSRevitNodes.Elements.DSModelText..ctor(String text, SketchPlane sketchPlane, Double xCoordinateInPlane, Double yCoordinateInPlane, Double textDepth, ModelTextType modelTextType) in c:\Users\boyerp\Dropbox\Github\Autodesk\DynamoNew\Dynamo\src\DSRevitNodes\Elements\DSModelText.cs:line 94
   at DSRevitNodes.Elements.DSModelText.ByTextSketchPlaneAndPosition(String text, DSSketchPlane sketchPlane, Double xCoordinateInPlane, Double yCoordinateInPlane, Double textDepth, DSModelTextType modelTextType) in c:\Users\boyerp\Dropbox\Github\Autodesk\DynamoNew\Dynamo\src\DSRevitNodes\Elements\DSModelText.cs:line 267
   at DSRevitNodesTests.Elements.ModelTextTests.&lt;&gt;c__DisplayClass4.&lt;ByTextSketchPlaneAndPosition_BadArgs&gt;b__0() in c:\Users\boyerp\Dropbox\Github\Autodesk\DynamoNew\Dynamo\src\DSRevitNodesTests\Elements\ModelTextTests.cs:line 67
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)
</message>
              <stack-trace>   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)
   at NUnit.Framework.Assert.Throws(Type expectedExceptionType, TestDelegate code)
   at DSRevitNodesTests.Elements.ModelTextTests.ByTextSketchPlaneAndPosition_BadArgs() in c:\Users\boyerp\Dropbox\Github\Autodesk\DynamoNew\Dynamo\src\DSRevitNodesTests\Elements\ModelTextTests.cs:line 67</stack-trace>
            </failure>
          </test-case>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>