<?xml version="1.0" encoding="utf-8"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\boyerp\Dropbox\Github\Autodesk\DynamoNew\Dynamo\bin\AnyCPU\Debug\DynamoTestFramework.dll" total="1" failures="0" not-run="0" date="2013-12-10" time="14:38:26" errors="1" inconclusive="0" ignored="0" skipped="0" invalid="0">
  <test-suite name="DynamoTestFrameworkTests" description="Unit tests in Revit." time="0.2830283" asserts="0" type="TestFixture" result="Success" executed="True">
    <results>
      <test-suite name="ProtoToRevitCurveTests" description="Unit tests in Revit." time="0.2830283" asserts="0" type="TestFixture" result="Success" executed="True">
        <results>
          <test-case name="BSplineCurve_Basic" success="False" time="0.2830283" executed="True" asserts="0" result="Error">
            <failure>
              <message>System.Exception : BSplineCurve.ByControlVertices operation failed</message>
              <stack-trace>   at Autodesk.DesignScript.Geometry.BSplineCurve.ByControlVerticesCore(Point[] controlVertices, Int32&amp; degree, Boolean makePeriodic)
   at Autodesk.DesignScript.Geometry.BSplineCurve..ctor(Point[] controlVertices, Int32 degree, Boolean makePeriodic, Boolean persist)
   at Autodesk.DesignScript.Geometry.BSplineCurve.ByControlVertices(Point[] controlVertices, Int32 degree, Boolean makePeriodic)
   at Autodesk.DesignScript.Geometry.BSplineCurve.ByControlVertices(Point[] controlVertices, Int32 degree)
   at DSRevitNodesTests.GeometryConversion.ProtoToRevitCurveTests.BSplineCurve_Basic() in c:\Users\boyerp\Dropbox\Github\Autodesk\DynamoNew\Dynamo\src\DSRevitNodesTests\GeometryConversion\ProtoToRevitCurveTests.cs:line 35</stack-trace>
            </failure>
          </test-case>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>